x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  node:
    build:
      context: ./hyperliquid
      args:
        - PUB_KEY_URL=${PUB_KEY_URL}
        - USERNAME=${USERNAME:-hyperliquid}
        - CHAIN=${CHAIN:-Mainnet}
    image: hyperliquid:local
    user: "${USERNAME:-hyperliquid}"
    restart: unless-stopped
    environment:
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
      - CHAIN=${CHAIN:-Mainnet}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_EVM_RPC=${ENABLE_EVM_RPC:-false}
      - NODE_TYPE=${NODE_TYPE:-non-validator}
      - VALIDATOR_PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY:-}
      - MAINNET_ROOT_IPS=${MAINNET_ROOT_IPS}
      - TESTNET_ROOT_IPS=${TESTNET_ROOT_IPS}
    ports:
      - ${P2P_PORT_RANGE:-4000-4010}:${P2P_PORT_RANGE:-4000-4010}/tcp
      - ${EVM_RPC_PORT:-3001}:${EVM_RPC_PORT:-3001}/tcp
    <<: *logging
    volumes:
      - consensus-data:/home/${USERNAME}/hl/data
    # entrypoint: ["bash"]
    # stdin_open: true   # - keeps STDIN open
    # tty: true
    entrypoint: ["docker-entrypoint.sh"]
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.${RPC_HOST:-hyperliquid}.service=${RPC_HOST:-hyperliquid}
    #   - traefik.http.routers.${RPC_HOST:-hyperliquid}.entrypoints=websecure
    #   - traefik.http.routers.${RPC_HOST:-hyperliquid}.rule=Host(`${RPC_HOST:-hyperliquid}.${DOMAIN:-local}`)
    #   - traefik.http.routers.${RPC_HOST:-hyperliquid}.tls.certresolver=letsencrypt
    #   - traefik.http.services.${RPC_HOST:-hyperliquid}.loadbalancer.server.port=${ETH_RPC_PORT:-3001}
    #   - metrics.scrape=true
    #   - metrics.path=/metrics
    #   - metrics.port=${ETH_RPC_PORT:-3001}
    #   - metrics.instance=${RPC_HOST:-hyperliquid}
    #   - metrics.network=${CHAIN:-Mainnet}

  # pruner:
  #   restart: unless-stopped
  #   build:
  #     context: ./hyperliquid/pruner
  #     args:
  #       - USERNAME=${USERNAME:-hyperliquid}
  #   volumes:
  #     - consensus-data:/home/${USERNAME}/hl/data
  #   image: hyperliquid-pruner:local
  #   pull_policy: never
  #   user: root
  #   stop_grace_period: 10s
  #   environment:
  #     - PRUNE_SCHEDULE=${PRUNE_SCHEDULE:-0 3 * * *}
  #     - PRUNE_RETAIN_DAYS=${PRUNE_RETAIN_DAYS:-7}
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #   <<: *logging

volumes:
  consensus-data:
