x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    build:
      context: ./hyperliquid
      args:
        - PUB_KEY_URL=${PUB_KEY_URL}
        - USERNAME=${USERNAME:-hyperliquid}
        - CHAIN=${CHAIN:-Mainnet}
    image: hyperliquid:local
    pull_policy: never
    user: "${USERNAME:-hyperliquid}"
    restart: unless-stopped
    environment:
      - CHAIN=${CHAIN:-Mainnet}
      - NODE_TYPE=${NODE_TYPE:-non-validator}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_EVM_RPC=${ENABLE_EVM_RPC:-false}
      - VALIDATOR_PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY:-}
      - MAINNET_ROOT_IPS=${MAINNET_ROOT_IPS:-}
      - TESTNET_ROOT_IPS=${TESTNET_ROOT_IPS:-}
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
      - FIREWALL_IPS=${FIREWALL_IPS:-}
    ports:
      - ${P2P_PORT_RANGE:-4000-4010}:${P2P_PORT_RANGE:-4000-4010}/tcp
      - ${P2P_PORT_RANGE:-4000-4010}:${P2P_PORT_RANGE:-4000-4010}/udp
    <<: *logging
    volumes:
      - consensus-data:/home/${USERNAME}
    entrypoint: ["docker-entrypoint.sh"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST}.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}.rule=Host(`${RPC_HOST}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST}lb.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}lb.rule=Host(`${RPC_LB}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST}.loadbalancer.server.port=${EVM_RPC_PORT}
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=${EVM_RPC_PORT}
      - metrics.instance=${RPC_HOST}
      - metrics.network=${CHAIN}

  pruner:
    build:
      context: ./pruner
      args:
        - USERNAME=${USERNAME:-hyperliquid}
    image: hyperliquid-pruner:local
    pull_policy: never
    user: root
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - consensus-data:/home/${USERNAME}
    depends_on:
      - consensus
    <<: *logging


  validator-info:
    profiles: ["tools"]
    image: curlimages/curl:latest
    user: root
    container_name: validator-info
    environment:
      - CHAIN=${CHAIN:-Testnet}
    entrypoint:
      - /bin/sh
      - -c
      - |
          # 1) Install deps (quietly)
          apk add --no-cache bash jq >/dev/null

          # 2) Re-exec into Bash and run the real work
          exec /bin/bash -c '
            echo "CHAIN set to: $${CHAIN:-Testnet}" >&2

            if [ "$${CHAIN:-Testnet}" = "Mainnet" ]; then
              URL="https://api.hyperliquid.xyz/info"
            else
              URL="https://api.hyperliquid-testnet.xyz/info"
            fi

            echo "Querying validator summaries from: $$URL" >&2
            curl -sS -X POST -H "Content-Type: application/json" \
                --data "{\"type\":\"validatorSummaries\"}" "$$URL" | jq .

            echo "Done." >&2
          '
    <<: *logging

  cli:
    profiles: ["tools"]
    build:
      context: ./hyperliquid
      args:
        - PUB_KEY_URL=${PUB_KEY_URL}
        - USERNAME=${USERNAME:-hyperliquid}
        - CHAIN=${CHAIN:-Mainnet}
    image: hyperliquid:local
    pull_policy: never
    user: "${USERNAME:-hyperliquid}"
    container_name: hyperliquid-cli
    environment:
      - CHAIN=${CHAIN:-Mainnet}
      - NODE_TYPE=${NODE_TYPE:-non-validator}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_EVM_RPC=${ENABLE_EVM_RPC:-false}
      - VALIDATOR_PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY:-}
      - MAINNET_ROOT_IPS=${MAINNET_ROOT_IPS:-}
      - TESTNET_ROOT_IPS=${TESTNET_ROOT_IPS:-}
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
    volumes:
      - consensus-data:/home/${USERNAME}
    entrypoint:
      - /bin/bash
      - -c
      - |
        if [ $# -eq 0 ]; then
          echo "Hyperliquid CLI Tool - Interactive Mode"
          exec bash
        else
          echo "Hyperliquid CLI Tool:"
          exec "$@"
        fi
      - --
    <<: *logging



volumes:
  consensus-data:
